{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintGrammar.
--   Generated by the BNF converter.

module Grammar.PrintGrammar where

import qualified Grammar.AbsGrammar as AG
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AG.Ident where
  prt _ (AG.Ident i) = doc (showString i)

instance Print AG.Prog where
  prt i e = case e of
    AG.Prog stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print [AG.Stmt] where
  prt = prtList

instance Print AG.Stmt where
  prt i e = case e of
    AG.SDef id expr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    AG.SEmpty -> prPrec i 0 (concatD [doc (showString ";")])
    AG.SBlock block -> prPrec i 0 (concatD [prt 0 block])
    AG.SAss id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    AG.SRet expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AG.SVRet -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AG.SIf expr block -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AG.SIfElse expr block ifcont -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block, prt 0 ifcont])
    AG.SWhile expr block -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AG.SExpr expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AG.Block where
  prt i e = case e of
    AG.Block stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print AG.IfCont where
  prt i e = case e of
    AG.SElif expr block -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block])
    AG.SElifElse expr block ifcont -> prPrec i 0 (concatD [doc (showString "elif"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block, prt 0 ifcont])
    AG.SElse block -> prPrec i 0 (concatD [doc (showString "else"), prt 0 block])

instance Print AG.Type where
  prt i e = case e of
    AG.TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    AG.TInt -> prPrec i 0 (concatD [doc (showString "int")])
    AG.TStr -> prPrec i 0 (concatD [doc (showString "str")])
    AG.TBool -> prPrec i 0 (concatD [doc (showString "bool")])
    AG.TFunc partypes type_ -> prPrec i 0 (concatD [doc (showString "("), prt 0 partypes, doc (showString "->"), prt 0 type_, doc (showString ")")])

instance Print AG.ParType where
  prt i e = case e of
    AG.ValPar type_ -> prPrec i 0 (concatD [prt 0 type_])
    AG.VarPar type_ -> prPrec i 0 (concatD [doc (showString "&"), prt 0 type_])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AG.ParType] where
  prt = prtList

instance Print AG.AddOp where
  prt i e = case e of
    AG.OPlus -> prPrec i 0 (concatD [doc (showString "+")])
    AG.OMinus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AG.MulOp where
  prt i e = case e of
    AG.OTimes -> prPrec i 0 (concatD [doc (showString "*")])
    AG.ODiv -> prPrec i 0 (concatD [doc (showString "/")])
    AG.OMod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AG.RelOp where
  prt i e = case e of
    AG.OLt -> prPrec i 0 (concatD [doc (showString "<")])
    AG.OLte -> prPrec i 0 (concatD [doc (showString "<=")])
    AG.OGt -> prPrec i 0 (concatD [doc (showString ">")])
    AG.OGte -> prPrec i 0 (concatD [doc (showString ">=")])
    AG.OEq -> prPrec i 0 (concatD [doc (showString "==")])
    AG.ONeq -> prPrec i 0 (concatD [doc (showString "!=")])

instance Print AG.Expr where
  prt i e = case e of
    AG.EVar id -> prPrec i 7 (concatD [prt 0 id])
    AG.EInt n -> prPrec i 7 (concatD [prt 0 n])
    AG.ETrue -> prPrec i 7 (concatD [doc (showString "true")])
    AG.EFalse -> prPrec i 7 (concatD [doc (showString "false")])
    AG.EStr str -> prPrec i 7 (concatD [prt 0 str])
    AG.EFunc args type_ block -> prPrec i 7 (concatD [doc (showString "fn"), doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 type_, prt 0 block])
    AG.EApp expr exprs -> prPrec i 6 (concatD [prt 7 expr, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AG.ENeg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AG.ENot expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AG.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AG.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AG.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AG.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AG.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AG.Arg] where
  prt = prtList

instance Print AG.Arg where
  prt i e = case e of
    AG.Arg id partype -> prPrec i 0 (concatD [prt 0 id, doc (showString ":"), prt 0 partype])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AG.Expr] where
  prt = prtList

